services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: reminder_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "0.0.0.0:8080:8080"
    env_file:
      - frontend/.env
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/reminder_service?sslmode=disable
      PORT: 8080
      # Auth0 Configuration - Must match frontend values
      AUTH0_DOMAIN: ${PUBLIC_AUTH0_DOMAIN:-dev.auth0.com}
      AUTH0_AUDIENCE: ${PUBLIC_AUTH0_AUDIENCE:-https://dev-p5vqcjkip31q2zci.us.auth0.com/api/v2/}
    depends_on:
      - postgres

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    volumes:
      - ./migrations:/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://user:password@postgres:5432/reminder_service?sslmode=disable
    depends_on:
      - postgres
    profiles:
      - migration

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5173:5173"
    env_file:
      - frontend/.env
    environment:
      # API Configuration
      - PUBLIC_API_BASE_URL=http://localhost:8080/api
      - PUBLIC_API_PORT=8080
      - PUBLIC_API_PATH=/api
      - PUBLIC_BACKEND_HOST=backend
      - BACKEND_API_URL=http://backend:8080/api
      # Auth0 Configuration - Replace with your values
      - PUBLIC_AUTH0_DOMAIN=${PUBLIC_AUTH0_DOMAIN:-your-domain.auth0.com}
      - PUBLIC_AUTH0_CLIENT_ID=${PUBLIC_AUTH0_CLIENT_ID:-your_client_id}
      - PUBLIC_AUTH0_AUDIENCE=${PUBLIC_AUTH0_AUDIENCE:-https://dev-p5vqcjkip31q2zci.us.auth0.com/api/v2/}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

volumes:
  postgres_data: