services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: reminder_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/reminder_service?sslmode=disable
      PORT: 8080
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5173:5173"
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:8080/api
      - PUBLIC_API_PORT=8080
      - PUBLIC_API_PATH=/api
      - PUBLIC_BACKEND_HOST=backend
      - BACKEND_API_URL=http://backend:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

volumes:
  postgres_data: