// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	KeyPrefix   string             `json:"key_prefix"`
	Permissions []byte             `json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryMethod struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Config    []byte             `json:"config"`
	Enabled   pgtype.Bool        `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID                      int32              `json:"id"`
	Title                   string             `json:"title"`
	Description             pgtype.Text        `json:"description"`
	ScheduledAt             pgtype.Timestamptz `json:"scheduled_at"`
	DeliveryMethod          string             `json:"delivery_method"`
	DeliveryAddress         string             `json:"delivery_address"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ReminderType            string             `json:"reminder_type"`
	NotificationChannels    []byte             `json:"notification_channels"`
	ScheduledTime           pgtype.Time        `json:"scheduled_time"`
	ScheduledDaysOfWeek     []int32            `json:"scheduled_days_of_week"`
	DeliveryWindowMinutes   int32              `json:"delivery_window_minutes"`
	IsActive                bool               `json:"is_active"`
	IsPersistent            bool               `json:"is_persistent"`
	AcknowledgedAt          pgtype.Timestamptz `json:"acknowledged_at"`
	ReminderIntervalMinutes pgtype.Int4        `json:"reminder_interval_minutes"`
	LastRemindedAt          pgtype.Timestamptz `json:"last_reminded_at"`
	UserID                  int32              `json:"user_id"`
	Category                string             `json:"category"`
	CompletedAt             pgtype.Timestamptz `json:"completed_at"`
	CompletionNote          pgtype.Text        `json:"completion_note"`
}

type ReminderStatistic struct {
	UserID               int32       `json:"user_id"`
	TotalReminders       int64       `json:"total_reminders"`
	CompletedReminders   int64       `json:"completed_reminders"`
	ActiveReminders      int64       `json:"active_reminders"`
	ThisWeekCount        int64       `json:"this_week_count"`
	LastWeekCount        int64       `json:"last_week_count"`
	ThisMonthCount       int64       `json:"this_month_count"`
	LastMonthCount       int64       `json:"last_month_count"`
	WeeklyChangePercent  interface{} `json:"weekly_change_percent"`
	MonthlyChangePercent interface{} `json:"monthly_change_percent"`
	CategoryBreakdown    []byte      `json:"category_breakdown"`
}

type User struct {
	ID            int32              `json:"id"`
	Auth0ID       string             `json:"auth0_id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	Picture       pgtype.Text        `json:"picture"`
	EmailVerified pgtype.Bool        `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
}
