// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryMethod struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Config    []byte             `json:"config"`
	Enabled   pgtype.Bool        `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID                    int32              `json:"id"`
	UserID                string             `json:"user_id"`
	Title                 string             `json:"title"`
	Description           pgtype.Text        `json:"description"`
	ScheduledAt           pgtype.Timestamptz `json:"scheduled_at"`
	DeliveryMethod        string             `json:"delivery_method"`
	DeliveryAddress       string             `json:"delivery_address"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ReminderType          string             `json:"reminder_type"`
	NotificationChannels  []byte             `json:"notification_channels"`
	ScheduledTime         pgtype.Time        `json:"scheduled_time"`
	ScheduledDaysOfWeek   []int32            `json:"scheduled_days_of_week"`
	DeliveryWindowMinutes int32              `json:"delivery_window_minutes"`
	IsActive              bool               `json:"is_active"`
}
