// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error)
	DeleteReminder(ctx context.Context, id int32) error
	GetActiveReminders(ctx context.Context) ([]Reminder, error)
	GetRecurringReminders(ctx context.Context) ([]Reminder, error)
	GetReminder(ctx context.Context, id int32) (Reminder, error)
	GetRemindersByUser(ctx context.Context, userID string) ([]Reminder, error)
	GetRemindersDueForDelivery(ctx context.Context) ([]Reminder, error)
	UpdateReminder(ctx context.Context, arg UpdateReminderParams) (Reminder, error)
	UpdateReminderStatus(ctx context.Context, arg UpdateReminderStatusParams) error
}

var _ Querier = (*Queries)(nil)
